INSERT INTO USUARIO (ID, NOME, LOGIN, SENHA, EMAIL, SITUACAO) VALUES (1, 'Adriano Pavaneli', 'adriano', '1234','adriano@gmail.com', 'ATIVO');

ALTER SEQUENCE USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE PERFIL_SEQ RESTART WITH 4;

INSERT INTO RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE RECURSO_SEQ RESTART WITH 4;